language: java
jdk:
  - oraclejdk8

script: mvn -q clean install
# whitelist
branches:
  only:
    - develop
services:
  - mysql
before_script:
  - mysql -u root -pcKp123654pKc -e 'create database spring_boot;'

notifications:
  email:
    - ckp_henu@163.com