language: java
jdk:
  - oraclejdk7

script: mvn -q clean install
# whitelist
branches:
  only:
    - develop
services:
  - mysql
env:
  - DB=mysql
mysql:
  database: es
  username: root
  password :
  encoding: utf8
before_script:
  - mysql -u root -e 'create database spring_boot'
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

notifications:
  email:
    - ckp_henu@163.com