language: java
jdk:
  - oraclejdk7

script: mvn -q clean install
# whitelist
branches:
  only:
    - develop
services:
  - mysql
before_script:
  - mysql -e 'create database spring_boot'

after_success:
- mvn clean cobertura:cobertura coveralls:report

notifications:
  email:
    - ckp_henu@163.com