language: java
jdk:
  - oraclejdk7

script: mvn -q clean install
# whitelist
branches:
  only:
    - develop
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
  - mysql -e 'create database spring_boot'
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

notifications:
  email:
    - ckp_henu@163.com